study/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sample/', include('sample.urls')),
    path('admin/', admin.site.urls),
]

study/login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
]

study/sample/urls.py
from django.urls import path
from sample import views

app_name = 'sample'
urlpatterns = [
    path('company/', views.CompanyList.as_view(), name='company_list'),
    path('balancingGroup/<int:company_id>/', views.BalancingGroupList.as_view(), name='balancing_group_list'),
    path('companyNavigation/', views.CompanyNavigation.as_view(), name='company_navigation'),
]

study/login/models.py
from django.db import models

# Create your models here.

study/sample/models.py
from django.db import models


class Company(models.Model):
    """事業者"""
    name = models.CharField('名称', max_length=255)

    def __str__(self):
        return self.name


class BalancingGroup(models.Model):
    """発電BG"""
    name = models.CharField('名称', max_length=255)
    company =  models.ForeignKey(Company, verbose_name='名称', related_name='balancing_groups', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class PowerPlant(models.Model):
    """発電所"""
    name = models.CharField('名称', max_length=255)
    balancing_group =  models.ForeignKey(BalancingGroup, verbose_name='名称', related_name='power_plants', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class Generator(models.Model):
    """発電機"""
    name = models.CharField('名称', max_length=255)
    power_plant =  models.ForeignKey(PowerPlant, verbose_name='名称', related_name='generator', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

study/login/views.py
from django.con.auth import login as auth_logon
from django.shortcuts import render, redirect
from django.urls import revers
from django.views import View

from .forms import LoginForm


class LoginView(View):
    def get(self, request, *args, **kwargs):
        """GETリクエスト用のメソッド"""
        context = {
            'from' : LoginForm(),
        }
        # ログイン画面用のテンプレートの値がからのフォームをレタリング
        return render(request, login/login.html, context)
        

study/sample/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView

from sample.models import Company


class CompanyList(ListView):
    """事業者一覧"""
    template_name='sample/company_list.html'
    context_object_name='companies'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        companies = Company.objects.all().order_by('id')
        self.object_list =companies
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)


class BalancingGroupList(ListView):
    """BG一覧"""
    template_name='sample/balancing_group_list.html'
    context_object_name='balancing_groups'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        company = get_object_or_404(Company, pk=kwargs['company_id'])
        balancing_groups = company.balancing_groups.all().order_by('id')
        self.object_list = balancing_groups
        context = self.get_context_data(object_list=self.object_list, company=company)
        return self.render_to_response(context)


class CompanyNavigation(View):
    """事業者ナビゲーション"""
    template_name='sample/company_navigation.html'

    def get(self, request, *args, **kwargs):
        company_navigation = [];
        
        companies = Company.objects.all().order_by('id')
        for company in companies:
            company_node = dict();
            company_node['text'] = company.name
            company_node['nodes'] = []
            company_navigation.append(company_node)

            balancing_groups = company.balancing_groups.all().order_by('id')
            for balancing_group in balancing_groups:
                balancing_group_node = dict();
                balancing_group_node['text'] = balancing_group.name
                balancing_group_node['nodes'] = []
                company_node['nodes'].append(balancing_group_node)
        return render(request, self.template_name, {'company_navigation': json.dumps(company_navigation)})

study/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:" en-us" }}">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-treeview.min.css' %}">
	{% block extra_css %}{% endblock %}
	<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
    <div class="container">
		{% block content %}
		{{ content }}
		{% endblock %}
    </div>
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/bootstrap-treeview.min.js' %}"></script>
	{% block extra_js %}{% endblock %}
</body>
</html>

study/templates/sample/balancing_group_list.html
{% extends "base.html" %}

{% block title %}BG一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">BG一覧</h4>

<h5 class="mt-2 border-bottom">
    <a href="{% url 'sample:company_list' %}">
        <small>{{ company.name }}</small>
    </a>
</h5>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">名称</th>
        </tr>
    </thead>
    <tbody>
        {% for balancing_group in balancing_groups %}
        <tr>
            <th scope="row">{{ balancing_group.id }}</th>
            <td>{{ balancing_group.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

study/templates/sample/company_list.html
{% extends "base.html" %}

{% block title %}事業者一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">事業者一覧</h4>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">名称</th>
			<th scope="col">操作</th>
		</tr>
	</thead>
	<tbody>
		{% for company in companies %}
		<tr>
			<th scope="row">{{ company.id }}</th>
			<td>{{ company.name }}</td>
			<td>
				<a href="{% url 'sample:balancing_group_list' company_id=company.id %}" class="btn btn-outline-info btn-sm">BG一覧</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock content %}

study/templates/sample/company_navigation.html
{% extends "base.html" %}

{% block title %}事業者ナビゲーション{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">事業者ナビゲーション</h4>
<p>
	<div id="navigation"></div>
</p>
{% endblock content %}

{% block extra_js %}
<script>
	var navigationData = JSON.parse('{{ company_navigation | safe }}');

	var setIcon = function(nodes){
		for (let node in nodes) {
			node.icon = "{% static 'css/bootstrap.min.css' %}";
		}
	}

    $('#navigation').treeview({
		data: navigationData,
		expandIcon: 'glyphicon glyphicon-plus'
	});
</script>
{% endblock %}